lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Erin, Dave, Jenna
  description: A wonderful pipeline for cell painting
  force: false
  is_nfcore: true
  name: cellpainting
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0dev
