lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  template_strings:
    - assets/cellprofiler/illumination.cppipe.jinja
    - modules/local/cellprofiler/illuminationcorrection/main.nf
  nextflow_config:
    - config_defaults:
        - params.cellprofiler_illumination_cppipe
        - params.cellprofiler_analysis_cppipe
        - params.cellprofiler_assaydevelopment_cppipe
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Kenneth Brewer
  description: A wonderful pipeline for cell painting
  force: false
  is_nfcore: true
  name: cellpainting
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 1.0.0dev
